# SPDX-License-Identifier: GPL-2.0
# Copyright(c) 2020 - 2023 Allwinner Technology Co.,Ltd. All rights reserved.

sun60i-g2d-y := sun60i-g2d-v4l2.o sun60i-g2d-formats.o sun60i-g2d-top.o \
		 sun60i-g2d-rcq.o sun60i-g2d-mixer.o
obj-$(CONFIG_VIDEO_SUN60I_G2D) += sun60i-g2d.o
