# SPDX-License-Identifier: GPL-2.0
#
CFLAGS += -I../ $(KHDR_INCLUDES)
TEST_GEN_PROGS := media_device_test media_device_open video_device_test \
		  sun60i_di_test
TEST_PROGS := sun60i_di_test.sh

include ../lib.mk
